name: CI/CD Pipeline

# Trigger this workflow on pushes or pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # step 2: Installing Docker
      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

      # Step 3: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Tag the existing 'latest' image with the version using GITHUB_RUN_NUMBER
      - name: Tag previous image with version
        run: |
          IMAGE_NAME="krishnakotalwar/local-web-app"
          VERSION_TAG="${{ github.run_number }}"
          docker pull ${IMAGE_NAME}:latest || true  # Pull latest image if it exists
          docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:${VERSION_TAG} || true
          docker push ${IMAGE_NAME}:${VERSION_TAG} || true

      - name: Build Docker image
        run: docker build -t local-web-app .

      - name: Push Docker image
        run: docker tag local-web-app krishnakotalwar/local-web-app:latest && docker push krishnakotalwar/local-web-app:latest

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible playbook
        run: ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i ansible/hosts.ini ansible/playbook.yml --extra-vars "ansible_sudo_pass=Krishna@123"

